namespace: openshift-operators
subscriptions:
  apicoperator:
    name: apic-operator
    subscription:
      channel: v2.5
      installPlanApproval: Automatic
      name: apic-operator
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace
